<?php

// This file is auto-generated by forge:models. Do not edit.

declare(strict_types=1);

namespace App\Domain\Contact\Model;

use Arcanum\Forge\ConnectionManager;
use Arcanum\Forge\Model as BaseModel;
use Arcanum\Forge\Result;

final class Model extends BaseModel
{
    public function createTable(): Result
    {
        return $this->execute(__DIR__ . '/CreateTable.sql', []);
    }

    public function findAll(): Result
    {
        return $this->execute(__DIR__ . '/FindAll.sql', []);
    }

    public function save(string $name, string $email, string $message): Result
    {
        return $this->execute(__DIR__ . '/Save.sql', ['name' => $name, 'email' => $email, 'message' => $message]);
    }
}
