<?php

// This file is auto-generated by forge:models. Do not edit.

declare(strict_types=1);

namespace App\Domain\Guestbook\Model;

use Arcanum\Flow\Sequence\Sequencer;
use Arcanum\Forge\Model as BaseModel;
use Arcanum\Forge\WriteResult;

final class Model extends BaseModel
{
    /**
     * @return Sequencer<array<string, mixed>>
     */
    public function allEntries(): Sequencer
    {
        return $this->read(__DIR__ . '/AllEntries.sql', []);
    }

    public function insertEntry(string $name, string $message): WriteResult
    {
        return $this->write(__DIR__ . '/InsertEntry.sql', ['name' => $name, 'message' => $message]);
    }
}
